"""empty message

Revision ID: 04af37f6ef8f
Revises: daa81e2eccd7
Create Date: 2019-01-14 16:58:51.912251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04af37f6ef8f'
down_revision = 'daa81e2eccd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'products', ['type_id'], ['type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
