"""empty message

Revision ID: daa81e2eccd7
Revises: 8ea302c16b91
Create Date: 2019-01-14 16:41:53.092071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa81e2eccd7'
down_revision = '8ea302c16b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type_id')
    # ### end Alembic commands ###
